ui: mocha-tdd

browsers:
  - name: chrome
    version: latest
  - name: firefox
    version: latest
  - name: safari
    version: latest
  - name: ie
    version: 10..latest

  - name: iphone
    version: latest
  - name: ipad
    version: latest
  - name: android
    version: latest

server: ./test/server/app.js
